volumes:
  php-fpm-socket:
  psysh-store:
  nuxt_node_modules:

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: shukatsu_backend
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./services/backend
        target: /work/backend
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: shukatsu_nginx
    ports:
      - ${HTTP_WEB_PORT}:80
      - ${HTTPS_WEB_PORT}:443
      - ${API_PORT}:9000
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./services/backend
        target: /work/backend
      - ${SSL_CRT_PATH}:/etc/nginx/certs/server.crt
      - ${SSL_KEY_PATH}:/etc/nginx/certs/server.key
      - ${SSL_PASS_PATH}:/etc/nginx/certs/server.password

  front:
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    container_name: shukatsu_front
    volumes:
      - ./services/frontend:/var/www/nuxt
      - nuxt_node_modules:/var/www/nuxt/node_modules
    ports:
      - ${FRONT_PORT}:3000
      - "24678:24678"
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run dev"
