volumes:
  php-fpm-socket:
  psysh-store:
  mysql-volume:
  node_modules_volume:

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: shukatsu_backend
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./services/backend
        target: /work/backend
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: shukatsu_nginx
    ports:
      - ${WEB_PORT}:80
      - "9000:9000"
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./services/backend
        target: /work/backend

  db:
    image: mysql:latest
    container_name: shukatsu_db
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - "3306:3306"

  front:
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    container_name: shukatsu_front
    volumes:
      - ./services/frontend:/var/www/nuxt
      - node_modules_volume:/var/www/nuxt/node_modules
    ports:
      - ${FRONT_PORT}:3000
      - "24678:24678"
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run dev"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: shukatsu_phpmyadmin
    ports:
      - "8888:80"
    depends_on:
      - db
